{{ if .Values.ingresses }}
{{ range .Values.ingresses }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if .ckanService }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .maxBodySize | default "1000M" }}
    {{ end }}
{{ if .extraConfig}}{{ .extraConfig | indent 4 }}{{ end }}
spec:
  {{ if .tls }}
  tls:
  - hosts:
    {{ range .rules }}
    - {{ .host }}
    {{ end }}
    secretName: ingress-{{ .name }}
  {{ end }}
  rules:
  {{ range .rules }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          serviceName: {{ .serviceName | default "ckan" }}
          servicePort: {{ .servicePort | default "5000" }}
        {{ if not .serviceName }}
        path: /(.*)
        {{ end }}
  {{ end }}
---
{{ end }}
{{ end }}
