{{ if not .Values.centralizedInfraOnly }}
apiVersion: apps/v1
kind: Deployment
metadata: {name: jobs-db}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels: {app: jobs-db}
  template:
    metadata:
      labels: {app: jobs-db}
    spec:
      {{ if .Values.ckanJobsDbTerminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.ckanJobsDbTerminationGracePeriodSeconds }}
      {{ end }}
      containers:
      - name: postgres
        image: postgres:12@sha256:31122316d7afefa1d99d843f3a1a09a5484304183ecff7ab943b8bb94ba44ba4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "123456"
        {{ if .Values.ckanJobsDbResources }}
        resources: {{ .Values.ckanJobsDbResources }}
        {{ end }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: ckan-data
          subPath: ckan-jobs-db
      volumes:
      - name: ckan-data
      {{ if .Values.usePersistentVolumes }}
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-jobs-db
      {{ else }}
        hostPath:
          path: /var/ckan-cloud-{{ .Release.Namespace }}
          type: DirectoryOrCreate
      {{ end }}
{{ end }}